import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { downloadHistory, listReportHistory } from '../api/reports'
import { ApiError } from '../api/client'
import type { ReportFormat, ReportHistoryList } from '../types/report'

export function ReportHistoryPage() {
  const [data, setData] = useState<ReportHistoryList | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [downloadingId, setDownloadingId] = useState<number | null>(null)

  function refresh() {
    setLoading(true)
    listReportHistory()
      .then(setData)
      .catch((err) => setError(err instanceof ApiError ? err.detail : String(err)))
      .finally(() => setLoading(false))
  }

  useEffect(() => {
    refresh()
  }, [])

  async function handleDownload(id: number, slug: string, format: string) {
    setDownloadingId(id)
    try {
      await downloadHistory(id, slug, format as ReportFormat)
      refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : String(err))
    } finally {
      setDownloadingId(null)
    }
  }

  return (
    <div className="max-w-6xl mx-auto px-8 py-8">
      <Link to="/reports" className="text-sm text-blue-600 hover:underline">
        ← All reports
      </Link>
      <header className="mt-2 mb-6">
        <h1 className="text-2xl font-bold text-slate-900">Export History</h1>
        <p className="text-sm text-slate-500">
          Every report exported across the platform. Re-downloads reflect <strong>current</strong> data —
          filters and report definition are reused, but the underlying companies may have changed.
        </p>
      </header>

      {error && (
        <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded-md p-3 mb-4">
          {error}
        </div>
      )}

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        {loading && <p className="p-6 text-sm text-slate-500">Loading…</p>}

        {!loading && data && data.items.length === 0 && (
          <p className="p-6 text-sm text-slate-500 text-center">
            No exports yet. Run a report from the <Link to="/reports" className="text-blue-600 hover:underline">reports page</Link> to populate this history.
          </p>
        )}

        {!loading && data && data.items.length > 0 && (
          <table className="w-full text-sm">
            <thead className="text-left text-xs uppercase tracking-wide text-slate-500 bg-slate-50 border-b border-slate-200">
              <tr>
                <th className="py-2 px-4">Time</th>
                <th className="py-2 px-4">Report</th>
                <th className="py-2 px-4">Filters</th>
                <th className="py-2 px-4">Format</th>
                <th className="py-2 px-4">Rows</th>
                <th className="py-2 px-4">Generated By</th>
                <th className="py-2 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {data.items.map((r) => (
                <tr key={r.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50">
                  <td className="py-2 px-4 text-slate-500 whitespace-nowrap">
                    {new Date(r.timestamp).toLocaleString()}
                  </td>
                  <td className="py-2 px-4 font-medium text-slate-900">{r.report_name}</td>
                  <td className="py-2 px-4 text-slate-600 text-xs font-mono">
                    {Object.keys(r.filters).length === 0
                      ? '—'
                      : Object.entries(r.filters)
                          .map(([k, v]) => `${k}=${v}`)
                          .join(' · ')}
                  </td>
                  <td className="py-2 px-4">
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded border uppercase bg-slate-100 text-slate-700 border-slate-200">
                      {r.format}
                    </span>
                  </td>
                  <td className="py-2 px-4 text-slate-700 tabular-nums">{r.row_count}</td>
                  <td className="py-2 px-4 text-slate-700">
                    <div>{r.user_name ?? '—'}</div>
                    <div className="text-xs text-slate-500">{r.user_email ?? ''}</div>
                  </td>
                  <td className="py-2 px-4 text-right">
                    <button
                      onClick={() => handleDownload(r.id, r.report_slug, r.format)}
                      disabled={downloadingId !== null}
                      className="text-xs text-blue-600 hover:underline disabled:opacity-50"
                    >
                      {downloadingId === r.id ? 'Downloading…' : 'Download again'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
